# Generated by Django 5.1.5 on 2025-02-10 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Описание категории', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок новости', max_length=255)),
                ('content', models.TextField(help_text='Содержимое новости')),
                ('published_date', models.DateTimeField(auto_now_add=True, help_text='Дата публикации')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Количество просмотров')),
                ('category', models.ForeignKey(help_text='Категория новости', on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.category')),
            ],
        ),
    ]
