# Generated by Django 5.1.6 on 2025-03-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_fix_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, help_text='Описание категории (английский)', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Описание категории (русский)', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='Название категории (английский)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Название категории (русский)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(help_text='Содержимое новости (английский)', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(help_text='Содержимое новости (русский)', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.TextField(blank=True, help_text='Краткое описание новости', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_en',
            field=models.TextField(blank=True, help_text='Краткое описание новости (английский)', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_ru',
            field=models.TextField(blank=True, help_text='Краткое описание новости (русский)', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(help_text='Заголовок новости (английский)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(help_text='Заголовок новости (русский)', max_length=255, null=True),
        ),
    ]
