# Generated by Django 5.1.5 on 2025-02-12 13:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-slug новости', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(help_text='Содержимое новости'),
        ),
    ]
