# Generated by Django 5.1.6 on 2025-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_description_en_category_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, help_text='Описание категории', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Описание категории', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='Название категории', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Название категории', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=models.TextField(help_text='Содержимое новости', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=models.TextField(help_text='Содержимое новости', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_en',
            field=models.TextField(blank=True, help_text='Краткое описание новости', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_ru',
            field=models.TextField(blank=True, help_text='Краткое описание новости', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(help_text='Заголовок новости', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(help_text='Заголовок новости', max_length=255, null=True),
        ),
    ]
