# Generated by Django 5.1.6 on 2025-03-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
