# Generated by Django 5.1.6 on 2025-03-05 11:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_category_options_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Описание категории', null=True, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, help_text='Описание категории', null=True, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Описание категории', null=True, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Название категории', max_length=255, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='Название категории', max_length=255, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Название категории', max_length=255, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(help_text='Категория новости', on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(help_text='Содержимое новости', verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=models.TextField(help_text='Содержимое новости', null=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=models.TextField(help_text='Содержимое новости', null=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение для новости', null=True, upload_to='news_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата публикации', verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(blank=True, help_text='Краткое описание новости', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_en',
            field=models.TextField(blank=True, help_text='Краткое описание новости', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_ru',
            field=models.TextField(blank=True, help_text='Краткое описание новости', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL слаг (автогенерация из заголовка)', null=True, unique=True, verbose_name='URL слаг'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Заголовок новости', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(help_text='Заголовок новости', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(help_text='Заголовок новости', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество просмотров', verbose_name='Просмотры'),
        ),
    ]
