# Generated by Django 5.1.6 on 2025-03-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Unicode-иконка для категории', max_length=10, null=True, verbose_name='Иконка'),
        ),
    ]
