# Generated by Django 5.1.6 on 2025-02-20 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания комментария')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего обновления')),
                ('is_approved', models.BooleanField(default=False, help_text='Одобрен ли комментарий модератором или AI')),
                ('author', models.ForeignKey(help_text='Автор комментария', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(help_text='Новость, к которой относится комментарий', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
                ('parent', models.ForeignKey(blank=True, help_text='Родительский комментарий (для организации древовидной структуры)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
