# Generated by Django 5.1.6 on 2025-02-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True, help_text='Ссылка на профиль Facebook', null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.URLField(blank=True, help_text='Ссылка на профиль Instagram', null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.URLField(blank=True, help_text='Ссылка на профиль Telegram', null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter',
            field=models.URLField(blank=True, help_text='Ссылка на профиль Twitter', null=True, verbose_name='Twitter'),
        ),
    ]
