# Generated by Django 5.1.6 on 2025-03-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='ru', help_text='Выберите язык интерфейса', max_length=10, verbose_name='Предпочитаемый язык'),
        ),
    ]
