# Generated by Django 5.1.6 on 2025-03-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_preferred_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='preferred_language',
        ),
    ]
