# Generated by Django 5.1.6 on 2025-02-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_facebook_customuser_instagram_and_more'),
        ('users', '0003_auto_20250218_2139'),
    ]

    operations = [
    ]
