# Generated by Django 5.1.6 on 2025-03-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_category_icon'),
        ('users', '0003_remove_customuser_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, help_text='Новости, добавленные пользователем в избранное', related_name='favorited_by', to='news.news', verbose_name='Избранные новости'),
        ),
    ]
