# Generated by Django 5.1.6 on 2025-02-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_social_networks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twitter',
        ),
    ]
