# Generated by Django 5.1.6 on 2025-02-23 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время постановки лайка')),
                ('news', models.ForeignKey(help_text='Новость, к которой поставлен лайк', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.news')),
                ('user', models.ForeignKey(help_text='Пользователь, поставивший лайк', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('news', 'user')},
            },
        ),
    ]
